import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {unzipSync,strFromU8} from 'fflate';
const base=process.env.SITE_URL||'http://127.0.0.1:4181/2026-PIDIS-lab/';
const {labs}=JSON.parse(await fs.readFile('src/data/labs.json','utf8'));const data=JSON.parse(await fs.readFile('src/data/variant-data.json','utf8'));const areas=JSON.parse(await fs.readFile('src/data/subject-areas.json','utf8')).subjectAreas;
await fs.mkdir('output/browser',{recursive:true});await fs.mkdir('quality',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const results={pages:0,sets:0,archives:[],errors};
async function download(button,name){const wait=page.waitForEvent('download',{timeout:180000});await button.click();const dl=await wait;const p='output/browser/'+name+'.zip';await dl.saveAs(p);const files=unzipSync(new Uint8Array(await fs.readFile(p)));return files;}
function checkZip(files,expected){const names=Object.keys(files);const htmls=names.filter(n=>n.endsWith('.html'));assert.equal(htmls.length,expected);for(const name of htmls){const h=strFromU8(files[name]);assert(h.includes('data:font/woff2;base64,'));assert(!/<script|<link|localhost|127\.0\.0\.1|PISID[34]-lecture/.test(h));assert(h.includes('Памятка для задачи'));const prefix=name.slice(0,-'Начните_здесь.html'.length);assert(files[prefix+'Шаблон_для_заполнения.docx']);const csv=names.filter(n=>n.startsWith(prefix+'Данные/')&&n.endsWith('.csv'));assert(csv.length>=2);for(const n of csv)assert(files[n][0]===239&&files[n][1]===187&&files[n][2]===191);}
 return htmls.length;
}
try{
 await page.goto(base,{waitUntil:'networkidle'});assert.equal(await page.locator('.lab-card').count(),20);await page.screenshot({path:'output/browser/catalog.png',fullPage:false});
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const lab of labs){await page.goto(base+'#/lab/'+lab.slug);await page.locator('#lab-title').waitFor();assert.equal(await page.locator('#lab-title').innerText(),lab.title);await page.locator('details').evaluateAll(ds=>ds.forEach(d=>d.open=true));assert.equal(await page.locator('.task-protocol>li').count(),lab.task.length);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert(!overflow,lab.id+': viewport overflow');results.pages++;} }
 await page.setViewportSize({width:1440,height:1000});
 for(const lab of labs){await page.goto(base+'#/lab/'+lab.slug);await page.locator('#lab-title').waitFor();for(const area of areas){await page.locator('select').selectOption(String(area.id));const expected=data[lab.id][area.id];const actual=await page.locator('#inputs table').evaluateAll(t=>t.map(x=>[...x.tBodies[0].rows].map(r=>[...r.cells].map(c=>c.textContent))));assert.deepEqual(actual,expected.map(s=>s.table.rows.map(r=>r.map(String))));results.sets++;}console.log('Data checked',lab.id);}
 await page.reload();assert.equal(await page.locator('select').inputValue(),'30');
 await page.goto(base+'#/lab/C3-S5-LR03');await page.locator('#lab-title').waitFor();await page.locator('select').selectOption('2');await page.locator('details').evaluateAll(ds=>ds.forEach(d=>d.open=true));await page.screenshot({path:'output/browser/lab.png',fullPage:true});
 let files=await download(page.locator('.student-start button').first(),'single');checkZip(files,1);assert(!Object.keys(files).some(n=>/manifest|assets|Состав_комплекта/.test(n)));const html=strFromU8(files['Начните_здесь.html']);assert(html.includes('PV02'));await fs.mkdir('output/browser/offline',{recursive:true});await fs.writeFile('output/browser/offline/start.html',html);
 const offline=await browser.newPage();await offline.route('https://**',route=>route.abort());await offline.goto(new URL('../output/browser/offline/start.html',import.meta.url).href.replace('/scripts/../','/'));await offline.screenshot({path:'output/browser/offline.png',fullPage:false});await offline.close();results.archives.push({scope:'single',sets:1});
 await page.goto(base);await page.getByRole('button',{name:'Комплект всех работ для варианта',exact:true}).click({trial:true});files=await download(page.getByRole('button',{name:'Комплект всех работ для варианта',exact:true}),'student-all');checkZip(files,20);assert(!Object.keys(files).some(n=>/manifest|assets|Состав_комплекта/.test(n)));results.archives.push({scope:'student-all',sets:20});
 await page.getByRole('button',{name:'Настройка перед занятием',exact:true}).click();
 for(const sem of [5,6,7,null]){const count=(sem?labs.filter(l=>l.semester===sem).length:labs.length)*30;files=await download(page.locator('dialog').getByRole('button',{name:sem?`${sem} семестр`:'Все семестры',exact:true}),'teacher-'+(sem||'all'));checkZip(files,count);results.archives.push({scope:'teacher-'+(sem||'all'),sets:count});console.log('Archive checked',sem,count);}
 assert.equal(errors.length,0);results.status='passed';
}catch(e){results.failure=String(e.stack);throw e}finally{await fs.writeFile('quality/browser.json',JSON.stringify(results,null,2));await browser.close()}
