import fs from 'node:fs';
import path from 'node:path';
import {designs} from '../authoring/design.mjs';
import {dataset} from '../authoring/datasets.mjs';
const root=path.resolve(import.meta.dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,data)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),typeof data==='string'?data:JSON.stringify(data,null,2))};
const old=read('authoring/original-labs.json'),variants=read('authoring/original-variants.json');
const version='pidis-2026.09-lab-v2';
const answers=fs.existsSync(path.join(root,'private/answer-model.mjs'))?(await import('../private/answer-model.mjs')).dataset:null;
const labs=[],methodology={},variantData={},teacher={},passports=[];
for(let i=0;i<old.length;i++){
 const o=old[i],d=designs[i];
 const parts=[Math.round(o.points*0.5*10)/10,Math.round(o.points*0.3*10)/10];parts.push(Math.round((o.points-parts[0]-parts[1])*10)/10);
 const rubric=[['Предметный результат',o.quality,parts[0]],['Проверка и обоснование','Конкретные ID, воспроизводимая проверка и объяснение ограничений.',parts[1]],['Трассировка и представление','Полнота связей, читаемая редактируемая форма, объяснение собственного решения.',parts[2]]];
 const lab={id:o.id,number:o.number,order:i,slug:o.id,title:o.title,block:o.semester-4,blockTitle:o.section,semester:o.semester,topicCode:'',topicTitle:o.section,points:o.points,practicalResult:o.artifact,situation:`Вы работаете с выбранной предметной областью {system}. ${o.goal} Используйте её роли и объекты, подтверждённые записи и ограничения. Решение должно учитывать конфликт: {conflict}.`,goal:o.goal,outcomes:[o.skill],sourceData:{intro:`Набор ${version}. Все данные учебные. Выбранный вариант определяет фактические записи.`,sections:[]},tools:['Редактор DOCX, табличный редактор с импортом CSV UTF-8 и разделителем «точка с запятой».','Для схем — доступный редактор диаграмм или читаемый рисунок с пояснением; платные инструменты не требуются.'],theoryCards:d.theory.map((s,j)=>({label:'Опора '+(j+1),title:s.split('|')[0],text:s.split('|')[1]})),task:d.steps.map(s=>s[0]),stages:d.steps.map(s=>s[0]),deliverables:[o.artifact,o.expected],evidence:[o.quality],selfCheck:[o.quality,'Каждое решение подтверждено ID или явно обозначенным допущением.','Проверен новый или граничный случай, ограничения вывода объяснены.'],wordRequirements:[`Используйте форму «${d.form}». ${o.expected}`,'Заполните поля своего варианта и добавляйте строки по необходимости. Не переписывайте целиком CSV: фиксируйте результаты и ID доказательств.','Приложите схемы и расчёты там, где они нужны для предметного результата. Передайте один редактируемый DOCX.'],professionalChoice:o.decision,lmsSteps:['Сохраните заполненный DOCX с фамилией, ID работы и вариантом.','Откройте соответствующее задание LMS и прикрепите файл.','Проверьте прикреплённый файл; объясните преподавателю основания решения и его проверку.'],reportFile:o.id+'.docx',recommendedFileName:o.id+'_Вариант_Фамилия.docx',rubric,version};
 labs.push(lab);
 methodology[o.id]={sequence:{previous:d.previous.length?`Используйте результаты ${d.previous.map(n=>old[n].id+' («'+old[n].artifact+'»)').join('; ')} своего варианта. Нужны только относящиеся к текущему шагу ID, поля и принятые ограничения.`:'Предыдущая работа не требуется. Начните с выданных документов и условий варианта.',next:designs.map((x,j)=>x.previous.includes(i)?old[j].id:null).filter(Boolean).length?'Сохраните '+o.artifact+': результат понадобится в '+designs.map((x,j)=>x.previous.includes(i)?old[j].id:null).filter(Boolean).join(', ')+'.':'Сохраните итоговую версию результата и основания решений.'},example:{title:'Разобранный пример на отдельных данных',source:d.example[0],method:[d.example[1]],result:d.example[2],boundary:'Записи EX не входят в оцениваемый набор. Примените способ к своему варианту.'},steps:d.steps.map((s,j)=>({data:s[1]+'. Таблицы текущего набора показаны выше; используйте их ID.',result:s[2],check:s[3],theory:d.theory[Math.min(j,d.theory.length-1)].split('|')[1]}))};
 variantData[o.id]={};teacher[o.id]={title:o.title,points:o.points,form:d.form,plannedMinutes:i<2?90:120+d.level*25,planningStatus:'Авторская оценка активной работы; пилот с начинающими студентами не проводился.',sourceDurationBlocks:fs.existsSync(path.join(root,'private/original/src/labs.json'))?read('private/original/src/labs.json')[i].durationBlocks:undefined,originalScenario:o.situation,partialCredit:'Оценивать результаты независимо в пределах рубрики; ошибка расчёта не обнуляет верную модель, если её связи и ограничения обоснованы.',rubric,hints:[d.theory[0].split('|')[1],d.steps[0][3],d.example.join(' ')],questions:[o.decision,'Покажите ID, на котором основано наиболее спорное решение.','Что изменится, если один подтверждённый источник будет отозван?'],modifiedCondition:'Владелец процесса меняет одно ограничение. Укажите затронутые строки и выполните повторную проверку.',variants:{}};
 for(const v of variants){const data=dataset(d,v);if(!data.sections.length)throw Error(d.key);variantData[o.id][v.id]=data.sections;teacher[o.id].variants[v.code]=answers?answers(d,v).keys:{status:"Закрытый модуль ответов не предоставлен"};passports.push({datasetId:`${o.id}-${v.code}-${version}`,labId:o.id,variantId:v.code,version,level:d.level,records:data.recordCount,files:data.sections.map((s,j)=>({name:`Данные_${String(j+1).padStart(2,'0')}.csv`,title:s.title,rows:s.table.rows.length})),previous:d.previous.map(n=>old[n].id),origin:'Авторские учебные данные на основе исходных кейсов и предметной области'});}
 const md=`# ${o.id} · ${o.title}\n\nСеместр ${o.semester}. Максимум ${o.points} баллов.\n\n${o.goal}\n\n${d.theory.map(s=>'## '+s.split('|')[0]+'\n\n'+s.split('|')[1]).join('\n\n')}\n\n## Действия\n\n${d.steps.map((s,j)=>`${j+1}. ${s[0]}. ${s[2]} Проверка: ${s[3]}`).join('\n')}\n\nВыдаваемый архив содержит условия выбранного варианта, все таблицы CSV и собственную форму DOCX.\n`;
 write(`content/course-${o.course}/semester-${o.semester}/${o.id}.md`,md);
 }
write('src/data/labs.json',{labs});write('src/data/variant-data.json',variantData);write('src/data/methodology.ts','export interface StepGuide {data:string;result:string;check:string;theory:string}\nexport const labMethodology: Record<string,{sequence:{previous:string;next:string};example:{title:string;source:string;method:string[];result:string;boundary:string};steps:StepGuide[]}> = '+JSON.stringify(methodology,null,2)+';\n');
write('src/data/subject-areas.json',{subjectAreas:variants.map(v=>({id:v.id,code:v.code,title:v.title,systemCode:v.system,description:v.process+'. '+v.conflict,criticalFunction:v.process,assets:v.objects,profileId:v.id,pack:v.code,roles:v.roles,conflict:v.conflict})),profiles:variants.map(v=>({id:v.id,title:'Условия '+v.code,variantRange:v.code,characteristics:[{code:'DOMAIN',name:'Процесс',value:v.process,example:'Учебная система '+v.system},{code:'ROLES',name:'Участники',value:v.roles.join(', '),example:'Технические полномочия администратора задаются отдельно.'},{code:'CHOICE',name:'Проектное противоречие',value:v.conflict,example:'Не снимайте ограничение без явного решения владельца процесса.'},{code:'VERSION',name:'Версия данных',value:version,example:'Перезагрузка и повторное скачивание не меняют набор.'}]}))});
write('private/teacher-guide.json',teacher);write('private/dataset-passports.json',passports);write('private/dependencies.json',designs.map((d,i)=>({id:old[i].id,previous:d.previous.map(n=>old[n].id),result:old[i].artifact,form:d.form,level:d.level,newData:d.key})));
if(fs.existsSync(path.join(root,'private/original/src/labs.json')))write('private/lecture-map.json',read('private/original/src/labs.json').map((l,i)=>({labId:l.id,lectures:l.lectures,methods:designs[i].theory.map(s=>s.split('|')[0]),actions:designs[i].steps.map(s=>s[0]),result:l.artifact})));
console.log(JSON.stringify({labs:labs.length,variants:variants.length,datasets:passports.length,records:passports.reduce((n,p)=>n+p.records,0)}));

write('authoring/docx-designs.json',designs);
